

function KeyConfigActionType.getKeyTypeName(self, keyType)
  local keyTypeNames = self.keyTypeNameById
  if keyTypeNames[self.INVENTORY] == nil then
    keyTypeNames[self.EQUIP] = "EQUIP"
    keyTypeNames[self.INVENTORY] = "INVENTORY"
    keyTypeNames[self.TO_ALL] = "TO_ALL"
    keyTypeNames[self.WHISPER] = "WHISPER"
    keyTypeNames[self.TO_PARTY] = "TO_PARTY"
    keyTypeNames[self.TO_FRIEND] = "TO_FRIEND"
    keyTypeNames[self.SHORTCUT] = "SHORTCUT"
    keyTypeNames[self.QUICKSLOT] = "QUICKSLOT"
    keyTypeNames[self.CHATPLUS] = "CHATPLUS"
    keyTypeNames[self.GUILD] = "GUILD"
    keyTypeNames[self.TO_GUILD] = "TO_GUILD"
    keyTypeNames[self.PARTY] = "PARTY"
    keyTypeNames[self.ABILITY] = "ABILITY"
    keyTypeNames[self.NOTIFICATION] = "NOTIFICATION"
    keyTypeNames[self.MONSTERBOOK] = "MONSTERBOOK"
    keyTypeNames[self.CASHSHOP] = "CASHSHOP"
    keyTypeNames[self.TO_ALLIANCE] = "TO_ALLIANCE"
    keyTypeNames[self.FIND_PARTY] = "FIND_PARTY"
    keyTypeNames[self.FAMILY] = "FAMILY"
    keyTypeNames[self.MEDAL] = "MEDAL"
    keyTypeNames[self.EXPEDITION] = "EXPEDITION"
    keyTypeNames[self.TO_EXPEDITION] = "TO_EXPEDITION"
    keyTypeNames[self.SKILL] = "SKILL"
    keyTypeNames[self.FRIEND] = "FRIEND"
    keyTypeNames[self.WORLDMAP] = "WORLDMAP"
    keyTypeNames[self.LOOT] = "LOOT"
    keyTypeNames[self.SIT] = "SIT"
    keyTypeNames[self.ATTACK] = "ATTACK"
    keyTypeNames[self.JUMP] = "JUMP"
    keyTypeNames[self.CHAT_NPC] = "CHAT_NPC"
    keyTypeNames[self.TO_CHANNEL] = "TO_CHANNEL"
    keyTypeNames[self.DPS] = "DPS"
    keyTypeNames[self.MESSENGER] = "MESSENGER"
    keyTypeNames[self.MINIMAP] = "MINIMAP"
    keyTypeNames[self.QUEST] = "QUEST"
    keyTypeNames[self.KEYCONFIG] = "KEYCONFIG"
    keyTypeNames[self.EMOTION_1] = "EMOTION_1"
    keyTypeNames[self.EMOTION_2] = "EMOTION_2"
    keyTypeNames[self.EMOTION_3] = "EMOTION_3"
    keyTypeNames[self.EMOTION_4] = "EMOTION_4"
    keyTypeNames[self.EMOTION_5] = "EMOTION_5"
    keyTypeNames[self.EMOTION_6] = "EMOTION_6"
    keyTypeNames[self.EMOTION_7] = "EMOTION_7"
    keyTypeNames[self.CHAT] = "CHAT"
  end
  return keyTypeNames[keyType] or ""
end
